package cu.suitetecsa.cubacelmanager.domain.model

import cu.suitetecsa.cubacelmanager.data.entyties.Balance as EntityBalance

data class Balance(
    val subscriptionID: Int,
    val credit: Double = 0.0,
    val activeUntil: Long = 0L,
    val dueDate: Long = 0L,
    val usageBasedPricing: Boolean = false,
    val data: Long? = null,
    val dataLte: Long? = null,
    val dataRemainingDays: Int? = null,
    val dailyData: Long? = null,
    val dailyDataRemainingHours: Int? = null,
    val mailData: Long? = null,
    val mailDataRemainingDays: Int? = null,
    val voice: Long? = null,
    val voiceRemainingDays: Int? = null,
    val sms: Int? = null,
    val smsRemainingDays: Int? = null,
    val bonusCredit: Double? = null,
    val bonusCreditDueDate: Long? = null,
    val bonusUnlimitedDataDueDate: Long? = null,
    val bonusData: Long? = null,
    val bonusDataLte: Long? = null,
    val bonusDataDueDate: Long? = null,
    val bonusDataCu: Long? = null,
    val bonusDataCuDueDate: Long? = null,
)

internal fun Balance.toEntity() = EntityBalance(
    subscriptionID = this.subscriptionID,
    credit = this.credit,
    activeUntil = this.activeUntil,
    dueDate = this.dueDate,
    usageBasedPricing = this.usageBasedPricing,
    data = this.data,
    dataLte = this.dataLte,
    dataRemainingDays = this.dataRemainingDays,
    dailyData = this.dailyData,
    dailyDataRemainingHours = this.dailyDataRemainingHours,
    mailData = this.mailData,
    mailDataRemainingDays = this.mailDataRemainingDays,
    voice = this.voice,
    voiceRemainingDays = this.voiceRemainingDays,
    sms = this.sms,
    smsRemainingDays = this.smsRemainingDays,
    bonusCredit = this.bonusCredit,
    bonusCreditDueDate = this.bonusCreditDueDate,
    bonusUnlimitedDataDueDate = this.bonusUnlimitedDataDueDate,
    bonusData = this.bonusData,
    bonusDataLte = this.bonusDataLte,
    bonusDataDueDate = this.bonusDataDueDate,
    bonusDataCu = this.bonusDataCu,
    bonusDataCuDueDate = this.bonusDataCuDueDate
)
