[versions]
activity-compose = "1.8.2"

androidx-junit = "1.1.5"
apklisupdate-non-view = "321dd1c817"
hilt-android = "2.50"

arturbosch-detekt = "1.23.1"
detekt-rules-compose = "1.3.0"

firebase-appdistribution-gradle = "4.0.1"
firebase-crashlytics-gradle = "2.9.9"
google-services = "4.4.0"
gradle = "8.1.4"
junit = "4.13.2"
kotlin-gradle-plugin = "1.9.21"
firebase-bom = "32.7.0"

compose-bom = "2023.10.01"
material-icons-extended = "1.5.4"

constraintlayout-compose = "1.0.1"

devtools-ksp = "1.9.21-1.0.16"
kotlin-android = "1.9.21"
agp = "8.2.0"
core-ktx = "1.12.0"
appcompat = "1.6.1"
coil-kt = "2.5.0"
espresso-core = "3.5.1"
material = "1.11.0"

lifecycle-runtime-ktx = "2.6.2"

navigation-compose = "2.7.6"
hilt-navigation-compose = "1.1.0"

datastore-preferences = "1.0.0"

suitetecsa-sdk-android = "71960127e6"

room-compiler = "2.6.1"
room-runtime = "2.6.1"
room-ktx = "2.6.1"

accompanist-permissions = "0.32.0"

lottie-compose = "6.0.1"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }

androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
apklisupdate-non-view = { module = "com.github.suitetecsa.apklisupdate:apklisupdate-non-view", version.ref = "apklisupdate-non-view" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt-android" }

detekt-rules-compose = { module = "ru.kode:detekt-rules-compose", version.ref = "detekt-rules-compose" }

firebase-appdistribution-gradle = { module = "com.google.firebase:firebase-appdistribution-gradle", version.ref = "firebase-appdistribution-gradle" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebase-crashlytics-gradle" }
google-services = { module = "com.google.gms:google-services", version.ref = "google-services" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-gradle-plugin" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material-icons-extended" }

androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayout-compose" }

androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }

coil-kt = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil-kt" }

core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }

androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-preferences" }

suitetecsa-sdk-android = { group = "com.github.suitetecsa", name = "sdk-android", version.ref = "suitetecsa-sdk-android" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room-compiler" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room-runtime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room-ktx" }

accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist-permissions" }

lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie-compose" }

[plugins]
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt-android" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "devtools-ksp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
arturbosch-detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "arturbosch-detekt" }
