name: App Publish
on:
  push:
    tags:
      - v*
    branches:
      - master
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-22.04
    if: ${{ startsWith(github.ref, 'refs/tags/v') && contains(github.repository_owner, 'InnovAppsSoft') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: Setup Java
        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc # v2.8.0

      - name: Generate App Version Name
        run: echo "VERSION_NAME=$(git describe --tags | sed 's/\(.*\)-/\1./' | sed 's/\(.*\)-/\1+/')" >> $GITHUB_ENV

      - name: Assemble release files
        run: ./gradlew assemble

      - name: Sign APK
        id: sign
        uses: r0adkll/sign-android-release@v1
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Get CHANGELOG.md message
        id: changelog
        run: |
          MESSAGE=$(awk '/^## \[v/{flag=1;next}/^## \[/{flag=0}flag' CHANGELOG.md)
          echo "::set-output name=message::$MESSAGE"

      - uses: xireiki/channel-post@v1
        name: Post Files
        with:
          bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          topic_id: ${{ secrets.TELEGRAM_TOPIC_ID }}
          context: ${{ steps.changelog.outputs.message }}
          path: ${{ steps.sign.outputs.signedReleaseFile }} # Total size does not exceed 50M
          parse_mode: Markdown # Optional
          method: sendFile
