package cu.suitetecsa.cubacelmanager.domain.model

import cu.suitetecsa.cubacelmanager.data.entyties.Balance as EntityBalance

data class Balance(
    val subscriptionID: Int,
    val credit: Double = 0.0,
    val activeUntil: Long = 0L,
    val dueDate: Long = 0L,
    val usageBasedPricing: Boolean = false,
    val data: Long? = null,
    val dataLte: Long? = null,
    val dataRemainingDays: Int? = null,
    val dailyData: Long? = null,
    val dailyDataRemainingHours: Int? = null,
    val mailData: Long? = null,
    val mailDataRemainingDays: Int? = null,
    val voice: Long? = null,
    val voiceRemainingDays: Int? = null,
    val sms: Int? = null,
    val smsRemainingDays: Int? = null,
    val bonusCredit: Double? = null,
    val bonusCreditRemainingDays: Int? = null,
    val bonusUnlimitedDataRemainingDays: Int? = null,
    val bonusData: Long? = null,
    val bonusDataLte: Long? = null,
    val bonusDataRemainingDays: Int? = null,
    val bonusVoice: Long? = null,
    val bonusVoiceRemainingDays: Int? = null,
    val bonusSms: Int? = null,
    val bonusSmsRemainingDays: Int? = null,
    val bonusDataCu: Long? = null,
    val bonusDataCuRemainingDays: Int? = null,
)

internal fun Balance.toEntity() = EntityBalance(
    subscriptionID = this.subscriptionID,
    credit = this.credit,
    activeUntil = this.activeUntil,
    dueDate = this.dueDate,
    usageBasedPricing = this.usageBasedPricing,
    data = this.data,
    dataLte = this.dataLte,
    dataRemainingDays = this.dataRemainingDays,
    dailyData = this.dailyData,
    dailyDataRemainingHours = this.dailyDataRemainingHours,
    mailData = this.mailData,
    mailDataRemainingDays = this.mailDataRemainingDays,
    voice = this.voice,
    voiceRemainingDays = this.voiceRemainingDays,
    sms = this.sms,
    smsRemainingDays = this.smsRemainingDays,
    bonusCredit = this.bonusCredit,
    bonusCreditRemainingDays = this.bonusCreditRemainingDays,
    bonusUnlimitedDataRemainingDays = this.bonusUnlimitedDataRemainingDays,
    bonusData = this.bonusData,
    bonusDataLte = this.bonusDataLte,
    bonusDataRemainingDays = this.bonusDataRemainingDays,
    bonusVoice = this.bonusVoice,
    bonusVoiceRemainingDays = this.bonusVoiceRemainingDays,
    bonusSms = this.bonusSms,
    bonusSmsRemainingDays = this.bonusSmsRemainingDays,
    bonusDataCu = this.bonusDataCu,
    bonusDataCuRemainingDays = this.bonusDataCuRemainingDays
)
